// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjcuiqgyuihverqdjrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0amN1aXFneXVpaHZlcnFkanJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjMxODAsImV4cCI6MjA2NDQzOTE4MH0.lgpz_uahkW-kr5kQafK-m-utnyM-gZo7dzcg6zxdHyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);